#lang sicp

(define (make-account balance secret)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (wrong-password x) "Incorrect password.")
  (define (dispatch pw m)
    (cond ((not (eq? pw secret)) wrong-password)
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request: MAKE-ACCOUNT" m))))
  dispatch)

(define a (make-account 5 'banana))
((a 'banana 'deposit) 10)
((a 'apple 'withdraw) 7)
((a 'banana 'withdraw) 2)